plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.0.0-beta8'
}

group = 'org.gooseapple'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url 'https://repo.xenondevs.xyz/releases'
    }
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    implementation("xyz.xenondevs.invui:invui:1.44")
    implementation 'org.mongodb:mongodb-driver-sync:5.3.0'
    compileOnly('xyz.jpenilla:squaremap-api:1.3.4')
    compileOnly('dev.folia:folia-api:1.21.4-R0.1-SNAPSHOT')
    //compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

shadowJar {
    archiveClassifier.set('') // Remove the '-all' suffix from the JAR file
    relocate 'com.mongodb', 'org.gooseapple.libs.mongodb' // Optional: Relocate MongoDB classes to avoid conflicts
    relocate 'org.bson', 'org.gooseapple.libs.bson' // Optional: Relocate BSON classes
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(localPropertiesFile.newDataInputStream())
}

def serverPluginsDir = localProperties.getProperty('server.plugins.dir', layout.buildDirectory.dir('libs').get().asFile.path)

tasks.register('copyJarToServer', Copy) {
    from tasks.named('shadowJar')
    into serverPluginsDir
}

tasks.named('shadowJar') {
    finalizedBy 'copyJarToServer'
}
